spring:
  cloud:
    stream:
      bindings:
        input:
          destination: legalbriefs
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 0
management:
  health:
    binders:
      enabled: true