spring:
  cloud:
    stream:
      bindings:
        myBinding:
          content-type: application/xml
          destination: igreyEx
          group: igreyGroup
      rabbit:
        bindings:
          myBinding:
            consumer:
              auto-bind-dlq:  true
              republish-to-dlq: true
              bindingRoutingKey: red
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 0
management:
  health:
    binders:
      enabled: true