spring:
  cloud:
    stream:
      bindings:
        xmlBinding:
#          content-type: application/xml
          destination: igreyEx
          group: igreyGroup1
        jsonBinding:
#          content-type: application/json
          destination: igreyEx
          group: igreyGroup2
      rabbit:
        bindings:
          xmlBinding:
            consumer:
              auto-bind-dlq:  true
              republish-to-dlq: true
              bindingRoutingKey: red
          jsonBinding:
            consumer:
              auto-bind-dlq:  true
              republish-to-dlq: true
              bindingRoutingKey: blue
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 0
management:
  health:
    binders:
      enabled: true