spring:
  cloud:
    stream:
      bindings:
        myBinding:
          destination: igreyEx
#          producer:
#            bindingRoutingKey: red
      rabbit:
        bindings:
          myBinding:
            producer:
              routing-key-expression: headers.type
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8088
management:
  health:
    binders:
      enabled: true